name: biapy
channels:
  - conda-forge
dependencies:
  - python
  - pip:
    - numpy
    - matplotlib
    - scikit-image
    - pandas
    - ipyvolume
    - pip
    - voila
    - itkwidgets
    - jupyterlab
    - nodejs
    - scikit-learn
    # - rise
    # - pyjnius=1.2.0
    - jupyter_contrib_nbextensions
    - ipympl
    - ipywidgets
    - numba>=0.43.1
    # - pyimagej
    # - openjdk=8
    - seaborn
    - plotnine 
    - napari
    - RISE
    - trackpy
    - tensorflow==1.15
    - tqdm
    - torch 
    - torchvision
    - mrc
    - stardist
    - cellpose
    - aicsimageio
    - xlrd
    - protobuf==3.20.*